name: Teleporters
version: '${project.version}'
main: oficina.warps.Teleporters
api-version: 1.19
authors: [ Leo13 ]
description: A plugin that adds warps commands.
commands:
  createwarp:
    description: That's how you create warps.
    permission: warp.create
    usage: /<command> <warpName>
  warp:
    description: Takes players to certain places.
    permission: warp.*
    usage: /<command> <WarpName>
  teleporters:
    description: General control of plugin.
    permission: teleporters.*
    usage: /<command> <argument>
  deletewarp:
    description: Delete a warp.
    permission: warp.delete
    usage: /<command> <WarpName>
permissions:
  warp.create:
    description: Allows players to create warps.
    default: op
  warp.*:
    description: Allows players to use warp command.
    default: op
  teleporters.*:
    description: Allows players to manage the plugin.
    default: op
  teleporters.reload:
    description: Allows players to reload the configuration.
    default: op
  warp.delete:
    description: Allows players to delete a warp.
    default: op