name: Warps
version: '${project.version}'
main: oficina.warps.Warps
api-version: 1.19
authors: [ Leo13 ]
description: A plugin that adds warps commands.
commands:
  createwarp:
    description: That's how you create warps.
    permission: warp.create
    usage: /<command> <warpName>
  warp:
    description: Takes players to certain places.
    permission: warp.*
    usage: /<command> <WarpName>
permissions:
  warp.create:
    description: Allows players to create warps.
    default: op
  warp.*:
    description: Allows players to use warp command.
    default: op